# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    person_repository:
        class: Doctrine\ODM\MongoDB\DocumentRepository
        factory: ["@doctrine.odm.mongodb.document_manager", getRepository]
        arguments: [ AppBundle\Document\Person ]

    user_service:
        class: AppBundle\Service\PersonService
        factory: ['AppBundle\Service\PersonService', createPersonService]
        arguments: [ '@person_repository' ]